torchrun --nproc_per_node 1 -m pretrain.run \
    --pretrain_method retromae \
    --model_name_or_path deepvk/moderna-small \
    --model_revision stage_3__50B_tok \
    --output_dir output \
    --train_data /hdd/TEXT_datasets/Wikipedia/ \
    --learning_rate 2e-4 \
    --num_train_epochs 1 \
    --per_device_train_batch_size 2 \
    --dataloader_drop_last True \
    --max_seq_length 4096 \
    --logging_steps 1 \
    --dataloader_num_workers 4 \
    --report_to wandb \
    --save_strategy epoch \
    --warmup_ratio 0.1 \
    --weight_decay 0.01 \
    --lr_scheduler_type inverse_sqrt \
    --encoder_mlm_probability 0.3 \
    --decoder_mlm_probability 0.5
